spring.application.name=SpringDemo
server.port=8080
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
spring.devtools.restart.enabled=false

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/virtual_banking}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.root=WARN
logging.level.com.example=INFO

spring.main.banner-mode=off
spring.jmx.enabled=false

server.servlet.context-path=/api